### PR TITLE
Angular, NGRX, TNS version bump to latest

### PR DESCRIPTION
**Pull request by jogboms**
Updated Angular to v4.x
Updated tns-core-modules
Updated nativescipt-angular
Updated ngrx- libraries

### CODE REVIEW

**Comment by jogboms** [comment]
still some more fixes to be done.

**Comment by jogboms** [comment]
I guess i had an error in my own codes. Open for merging... :)

**Comment by zbarbuto** [comment]
cc @vakrilov

**Review by vakrilov — COMMENTED** [review]
LGTM!

**Pull request merged**
